language: generic
sudo: required
dist: trusty

before_install:
  # Get llvm 3.9
  - wget http://releases.llvm.org/3.9.0/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - tar -xf clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - export PATH=$PWD/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04/bin/:$PATH
  - export LIBRARY_PATH=$PWD/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04/lib/:$LIBRARY_PATH

  - sudo apt-get -y install autoconf automake build-essential libtool
    python python-pip python-sklearn python-pygraphviz python-pydot libiomp-dev
    python-networkx python-jinja2 python-matplotlib google-perftools
    libgoogle-perftools-dev numactl dc zlib1g-dev libedit-dev

  # Install ronn
  - gem install ronn

  # Install pulp
  - sudo pip install pulp

install:
  - ./autogen.sh
  - ./configure --without-dragonegg
  - make
  - sudo make install
  - sudo ln -s /usr/lib/libiomp5.so /usr/lib/libomp.so
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

before_script:
  - cat config.log

script:
  - cd tests/
  - ./test.sh
  - cd ..
  - for i in $(find tests/ -maxdepth 1 -type d -name 'test_*' | sort ); do echo "************** TEST $i"; if [ ! -f "$i/fortran_test" ]; then cat $i/test.log; fi done;
